##datasource property
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
#spring.datasource.username=system
#spring.datasource.password=manager
##JPA-hibernet property
#spring.jpa.database-platform=org.hibernate.dialect.Oracle10gDialect
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update


spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: system
    url: jdbc:oracle:thin:@localhost:1521:xe
    password: manager
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    hibernate:
      ddl-auto: update
